name: 'Run changelog webhook action'
on:
  workflow_dispatch:
  push:
    branches:
      - 'changelog-webhook-test'
    paths: 
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          
      - run: npm ci
      
      - name: runFile
        run: node webhook.js
